# Generated by Django 4.2.7 on 2023-11-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=20, unique=True)),
                ('data_nascimento', models.DateField()),
                ('tipo_associacao', models.CharField(choices=[('fundador', 'Sócio Fundador'), ('proprietario', 'Sócio Proprietário'), ('cotista', 'Sócio Cotista'), ('voluntario', 'Sócio Voluntário')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=20, unique=True)),
                ('data_nascimento', models.DateField()),
                ('tipo_vinculo', models.CharField(choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('filho', 'Filho'), ('filha', 'Filha'), ('neto', 'Neto')], max_length=20)),
                ('socio_titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes_associado', to='Associados.associado')),
            ],
        ),
        migrations.AddField(
            model_name='associado',
            name='dependentes',
            field=models.ManyToManyField(blank=True, related_name='associados_dependente', to='Associados.dependente'),
        ),
    ]
