# Generated by Django 4.2.7 on 2023-11-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspacoLocavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tamanho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('capacidade_pessoas', models.PositiveIntegerField()),
                ('data_construcao_aquisicao', models.DateField()),
                ('locavel', models.BooleanField(default=True)),
            ],
        ),
    ]
